# Generated by Django 5.2.4 on 2025-09-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("innovapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="username",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
