# Generated by Django 4.2.16 on 2025-09-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovapp', '0002_testimonial_alter_customer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.CharField(help_text='Duration in minutes', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
