# Generated by Django 4.2.16 on 2025-09-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovapp', '0004_alter_service_duration_alter_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(default='fas fa-cogs', help_text='Font Awesome class e.g. fas fa-tools', max_length=100),
        ),
    ]
