# Generated by Django 5.2.4 on 2025-09-15 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("innovapp", "0002_alter_customer_username"),
        ("innovapp", "0005_service_icon"),
    ]

    operations = []
